fff

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -70,10 +70,24 @@ jobs:
         run: |
           & "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "CICD3.sln" /p:Configuration=Release /p:Platform="Any CPU"
 
+        Write-Host "==== Checking Release folders ===="
+
+        Get-ChildItem "${{ github.workspace }}" -Recurse -Directory |
+          Where-Object { $_.Name -eq "Release" } |
+          Select-Object FullName
+
+
       - name: Deploy Files
         shell: powershell
         run: |
           $source = "${{ github.workspace }}\CICD3\bin\Release"
+
+        Write-Host "Using source path: $source"
+
+          if (!(Test-Path $source)) {
+              Write-Error "Source path not found: $source"
+              exit 1
+          }
 
           if ("${{ inputs.deploy_qa }}" -eq "true") {
             Copy-Item "$source\*" "D:\Publish New\Environments\MyApp\QA" -Recurse -Force
